#Requires -Version 5.1
<#
.SYNOPSIS
    OrQuanta — One-shot Cloudflare deploy (Worker + Pages)

.DESCRIPTION
    1. Validates CF API token
    2. Deploys worker.js via wrangler (routes: orquanta.com/*, www.orquanta.com/*)
    3. Rebuilds React SPA with production env vars
    4. Deploys SPA to Cloudflare Pages
    5. Smoke-tests orquanta.com

.USAGE
    $env:CLOUDFLARE_API_TOKEN = "your-token-here"
    .\deploy-worker.ps1

    # Or inline:
    $env:CLOUDFLARE_API_TOKEN = "xxx" ; .\deploy-worker.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Colours ──────────────────────────────────────────────────────────────────
function Write-Step  { param($msg) Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Write-Ok    { param($msg) Write-Host "  ✓ $msg"  -ForegroundColor Green }
function Write-Warn  { param($msg) Write-Host "  ⚠ $msg"  -ForegroundColor Yellow }
function Write-Fail  { param($msg) Write-Host "  ✗ $msg"  -ForegroundColor Red; exit 1 }

# ── Config ───────────────────────────────────────────────────────────────────
$ACCOUNT_ID  = "2dd90fe6473410b2605b5b177d606599"
$ZONE_ID     = "ce15f8600b6f1cd8af8ebee53dd08608"
$WORKER_NAME = "orquanta-proxy"
$BACKEND_URL = "https://orquanta-sg.onrender.com"
$PAGES_PROJECT = "orquanta-app"
$ROOT = $PSScriptRoot

# ── 0. Token check ───────────────────────────────────────────────────────────
Write-Step "Checking CLOUDFLARE_API_TOKEN..."
$token = $env:CLOUDFLARE_API_TOKEN
if (-not $token -or $token.Length -lt 10) {
    Write-Fail "CLOUDFLARE_API_TOKEN is not set. Run: `$env:CLOUDFLARE_API_TOKEN = 'your-token'"
}
$headers = @{ Authorization = "Bearer $token"; "Content-Type" = "application/json" }

$verify = Invoke-RestMethod "https://api.cloudflare.com/client/v4/user/tokens/verify" `
    -Headers $headers -Method Get -ErrorAction SilentlyContinue
if ($verify.success) {
    Write-Ok "Token valid — status: $($verify.result.status)"
} else {
    Write-Fail "Invalid token. Check permissions: Workers Scripts:Edit, Workers Routes:Edit, Zone:Read"
}

# ── 1. Deploy Worker via wrangler ─────────────────────────────────────────────
Write-Step "Deploying Cloudflare Worker '$WORKER_NAME'..."
Push-Location $ROOT
try {
    $env:CLOUDFLARE_API_TOKEN = $token
    $env:CLOUDFLARE_ACCOUNT_ID = $ACCOUNT_ID

    npx wrangler deploy --config wrangler.toml 2>&1 | Tee-Object -Variable wranglerOut
    if ($LASTEXITCODE -ne 0) {
        Write-Fail "wrangler deploy failed. Output above."
    }
    Write-Ok "Worker deployed — routes: orquanta.com/* + www.orquanta.com/*"
} finally {
    Pop-Location
}

# ── 2. Verify Worker vars are set in CF dashboard ────────────────────────────
Write-Step "Checking Worker environment variables..."
$workerVarsUrl = "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/workers/scripts/$WORKER_NAME/settings"
$settings = Invoke-RestMethod $workerVarsUrl -Headers $headers -Method Get -ErrorAction SilentlyContinue
if ($settings.success) {
    $bindings = $settings.result.bindings | Where-Object { $_.type -eq "plain_text" }
    $hasBackend = ($bindings | Where-Object { $_.name -eq "BACKEND_URL" }).Count -gt 0
    if ($hasBackend) {
        Write-Ok "BACKEND_URL binding confirmed in Worker"
    } else {
        Write-Warn "BACKEND_URL not set as Worker binding — wrangler.toml [vars] will be used (OK for now)"
        Write-Warn "For production: CF Dashboard → Workers → $WORKER_NAME → Settings → Variables"
        Write-Warn "  BACKEND_URL = $BACKEND_URL"
    }
} else {
    Write-Warn "Could not read Worker settings (may need Zone:Read scope). Continuing..."
}

# ── 3. Rebuild React SPA ──────────────────────────────────────────────────────
Write-Step "Building React SPA (v4/frontend)..."
$frontendDir = Join-Path $ROOT "v4\frontend"

# Write correct production env
$prodEnvContent = @"
# OrQuanta Frontend — Production Build Config
# Generated by deploy-worker.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
VITE_API_BASE_URL=https://orquanta.com
VITE_WS_BASE_URL=wss://orquanta.com
VITE_APP_ENV=production
"@
Set-Content -Path (Join-Path $frontendDir ".env.production") -Value $prodEnvContent -Encoding UTF8
Write-Ok "Written .env.production (API → https://orquanta.com)"

Push-Location $frontendDir
try {
    npm run build -- --mode production 2>&1 | Tee-Object -Variable buildOut
    if ($LASTEXITCODE -ne 0) {
        Write-Fail "npm run build failed."
    }
    $distFiles = (Get-ChildItem "dist" -Recurse -File).Count
    Write-Ok "Build complete — $distFiles files in dist/"
} finally {
    Pop-Location
}

# ── 4. Deploy SPA to Cloudflare Pages ────────────────────────────────────────
Write-Step "Deploying frontend to Cloudflare Pages ($PAGES_PROJECT)..."
Push-Location $frontendDir
try {
    npx wrangler pages deploy dist `
        --project-name $PAGES_PROJECT `
        --branch main `
        --commit-message "deploy: $(Get-Date -Format 'yyyy-MM-dd HH:mm') via deploy-worker.ps1" `
        2>&1 | Tee-Object -Variable pagesOut

    if ($LASTEXITCODE -ne 0) {
        # Pages project may not exist yet — create it
        Write-Warn "Pages deploy failed. Attempting to create project '$PAGES_PROJECT'..."
        npx wrangler pages project create $PAGES_PROJECT --production-branch main 2>&1
        npx wrangler pages deploy dist `
            --project-name $PAGES_PROJECT `
            --branch main 2>&1 | Tee-Object -Variable pagesOut2
        if ($LASTEXITCODE -ne 0) {
            Write-Fail "Cloudflare Pages deploy failed. Check output above."
        }
    }
    Write-Ok "Pages SPA deployed successfully"
} finally {
    Pop-Location
}

# ── 5. Smoke test ─────────────────────────────────────────────────────────────
Write-Step "Smoke-testing https://orquanta.com ..."
Start-Sleep -Seconds 5  # brief propagation wait

$attempts = 0
$maxAttempts = 6
$success = $false
while ($attempts -lt $maxAttempts -and -not $success) {
    $attempts++
    try {
        $resp = Invoke-WebRequest -Uri "https://orquanta.com/health" `
            -UseBasicParsing -TimeoutSec 15 -ErrorAction Stop
        if ($resp.StatusCode -eq 200) {
            $body = $resp.Content | ConvertFrom-Json -ErrorAction SilentlyContinue
            Write-Ok "orquanta.com/health → HTTP $($resp.StatusCode) | status=$($body.status)"
            $success = $true
        }
    } catch {
        Write-Warn "Attempt $attempts/$maxAttempts — waiting 10s... ($_)"
        Start-Sleep -Seconds 10
    }
}

Write-Host ""
if ($success) {
    Write-Host "══════════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  🚀  OrQuanta is LIVE at https://orquanta.com"    -ForegroundColor Green
    Write-Host "  📊  Dashboard  : https://orquanta.com/app"        -ForegroundColor Green
    Write-Host "  🔍  API Docs   : https://orquanta.com/docs"       -ForegroundColor Green
    Write-Host "  💚  Health     : https://orquanta.com/health"     -ForegroundColor Green
    Write-Host "══════════════════════════════════════════════════" -ForegroundColor Cyan
} else {
    Write-Warn "Smoke test inconclusive — DNS may still be propagating."
    Write-Warn "Check manually: https://orquanta.com/health"
    Write-Warn "CF Worker logs: https://dash.cloudflare.com → Workers → $WORKER_NAME → Logs"
}
