"""
OrQuanta — Mojibake Character Fixer
=====================================
Fixes garbled characters (â€", ðŸ§, Â·, âš¡, etc.) in all demo/landing HTML files.

Root cause: UTF-8 text was read as Windows-1252 (Latin-1) at some point,
corrupting multi-byte emoji and special characters in the Python file strings.

Run: python fix_encoding.py
"""
import re

# Complete mojibake → correct character mapping
# Generated by encoding each char as UTF-8, then decoding as latin-1
FIXES = [
    # Em dashes and typography
    ('â€"',  '—'),   # U+2014 em dash
    ('â€"',  '–'),   # U+2013 en dash
    ('â€˜',  '\u2018'),  # ' left single quote
    ('â€™',  '\u2019'),  # ' right single quote
    ('â€œ',  '\u201C'),  # " left double quote
    ('â€\x9d', '\u201D'), # " right double quote
    ('â€',  '\u201D'),   # " right double quote (alt)
    ('Â·',  '\xB7'),     # · middle dot
    ('Â ',  '\xA0'),     # non-breaking space
    # Arrows
    ('â†'',  '→'),   # →
    ('â†"',  '↓'),   # ↓
    ('â†\x90', '←'),  # ←
    ('â†'',  '↑'),   # ↑
    ('âŸ¶',  '⟶'),  # ⟶ long arrow
    ('â†©',  '↩'),   # ↩
    # Check marks and X marks
    ('âœ"',  '✓'),   # ✓
    ('âœ…',  '✅'),  # ✅
    ('âœ—',  '✗'),   # ✗
    ('â€¢',  '•'),   # • bullet
    # Lightning / symbols
    ('âš¡',  '⚡'),   # ⚡
    ('âš™',  '⚙'),   # ⚙
    # 4-byte emoji (F0 9F ... pattern → ð + 3 chars)
    ('ðŸ§ ',  '🧠'),   # 🧠 brain
    ('ðŸ'¸',  '💸'),  # 💸 money with wings
    ('ðŸ"§',  '🔧'),  # 🔧 wrench
    ('ðŸ"'',  '🔒'),  # 🔒 lock
    ('ðŸ"Š',  '📊'),  # 📊 bar chart
    ('ðŸš€',  '🚀'),  # 🚀 rocket
    ('ðŸŒ¿',  '🌿'),  # 🌿 leaf
    ('ðŸ—ºï¸', '🗺️'), # 🗺️ map
    ('ðŸ†"',  '🆓'),  # 🆓 free
    ('ðŸ¤–',  '🤖'),  # 🤖 robot
    ('ðŸ'°',  '💰'),  # 💰 money bag
    ('ðŸ'µ',  '💵'),  # 💵 dollar
    ('ðŸŽ¯',  '🎯'),  # 🎯 target
    ('ðŸ"ˆ',  '📈'),  # 📈 chart up
    ('ðŸ"‰',  '📉'),  # 📉 chart down
    ('ðŸ"…',  '📅'),  # 📅 calendar
    ('ðŸ"Œ',  '📌'),  # 📌 pushpin
    ('ðŸ"‹',  '📋'),  # 📋 clipboard
    ('ðŸ'¡',  '💡'),  # 💡 light bulb
    ('ðŸ"',  '🔍'),  # 🔍 magnifying glass
    ('ðŸ"',  '🔎'),  # 🔎 magnifying glass right
    ('ðŸ›',  '🛡'),   # 🛡 shield
    ('ðŸŒ',  '🌍'),  # 🌍 earth
    ('ðŸ¤',  '🤝'),  # 🤝 handshake
    ('ðŸ'·',  '👷'),  # 👷 engineer
    # 3-byte sequences
    ('ã€œ',  '〜'),  # wave dash
]

FILES_TO_FIX = [
    r'v4\demo\public_demo.py',
    r'v4\landing\index.html',
    r'v4\api\main.py',        # has HTML for register/welcome pages
]

def fix_file(path: str) -> int:
    try:
        with open(path, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read()
    except FileNotFoundError:
        print(f'SKIP (not found): {path}')
        return 0
    
    original = content
    total_replacements = 0

    for bad, good in FIXES:
        count = content.count(bad)
        if count > 0:
            content = content.replace(bad, good)
            total_replacements += count
            print(f'  [{path}] Fixed {count}x: {repr(bad)} → {repr(good)}')

    if total_replacements > 0:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f'  ✅ Saved {path} ({total_replacements} fixes)')
    else:
        print(f'  ✓  Clean: {path}')

    return total_replacements


def fix_htmlresponse_charset(path: str) -> bool:
    """Ensure HTMLResponse calls include media_type with charset=utf-8."""
    try:
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
    except FileNotFoundError:
        return False

    original = content
    # Fix: HTMLResponse(...) → HTMLResponse(..., media_type="text/html; charset=utf-8")
    content = re.sub(
        r'HTMLResponse\(([^)]+)\)',
        lambda m: _fix_htmlresponse(m.group(0), m.group(1)),
        content
    )
    # Fix: return HTMLResponse(html) patterns
    if content != original:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f'  ✅ Fixed HTMLResponse charset in {path}')
        return True
    return False


def _fix_htmlresponse(full_match: str, args: str) -> str:
    if 'charset' in args or 'media_type' in args:
        return full_match  # already fixed
    # Add media_type to the call
    stripped = args.rstrip()
    if stripped.endswith(','):
        new_args = f'{stripped} media_type="text/html; charset=utf-8"'
    else:
        new_args = f'{stripped}, media_type="text/html; charset=utf-8"'
    return f'HTMLResponse({new_args})'


if __name__ == '__main__':
    print('=== OrQuanta Mojibake Fixer ===\n')
    total = 0
    for f in FILES_TO_FIX:
        total += fix_file(f)

    print('\n=== Fixing FastAPI HTMLResponse charset headers ===')
    for f in FILES_TO_FIX:
        if f.endswith('.py'):
            fix_htmlresponse_charset(f)

    print(f'\n✅ Done! Total characters fixed: {total}')
    if total == 0:
        print('   (Files may already be clean, or encoding is stored differently)')
        print('   → Check fast API Content-Type header instead')
